### ISSUE TITLE
`2.5.0` doesn't work with Python <`3.10`

### ISSUE THREAD

**Issue by thaiphv** [vgrem/Office365-REST-Python-Client#756]
The import `from office365.runtime.client_object import ClientObject` failed with the error:
```
ImportError: cannot import name 'ParamSpec' from 'typing' (/usr/lib/python3.8/typing.py)
```
Fro https://github.com/vgrem/Office365-REST-Python-Client/blob/2.5.0/office365/runtime/client_object.py#L11, `ParamSpec` wasn't imported conditionally.
