### ISSUE TITLE
AttributeError when using with_client_secret

### ISSUE THREAD

**Issue by AngPeiHao** [vgrem/Office365-REST-Python-Client#951]
`GraphClient.with_client_secret(TENANT_ID, CLIENT_ID, SERVICE_SECRET)` causes `AttributeError: 'str' object has no attribute 'pending_request'` in `office365/graph_client.py::with_client_secret`.

This error is only raised from version `2.6.0+` and works fine in `2.5.14`.

**Comment by vgrem** [comment]
Starting from version 2.6.0, the way the client is initialized has changed from:

`GraphClient.with_client_secret(TENANT_ID, CLIENT_ID, SERVICE_SECRET)`

into 

`GraphClient(TENANT_ID).with_client_secret(CLIENT_ID, SERVICE_SECRET)`

This change is not backward compatible, so existing implementations will need to be updated accordingly.
