### ISSUE TITLE
Error using FileCollection.add() since version 2.3.16

### ISSUE THREAD

**Issue by patrickvolz** [vgrem/Office365-REST-Python-Client#653]
Since version 2.3.15 I get this error when trying to upload a file to sharepoint:
FileCollection.add() missing 1 required positional argument: 'content'

It works with version 2.3.14. No change in code other than the version of the Office365-REST-Python-Client package.

What could be the root cause? Thank You,

**Comment by patrickvolz** [comment]
Will this ever be fixed or does anybody know a workaround.
I will try latest version to check if there is still the same problem...

**Comment by vgrem** [comment]
Closing - fixed in a subsequent release. `FileCollection.add(url, content, overwrite=False)` is back to its original signature. Please upgrade to the latest version.
