### ISSUE TITLE
Undocumented breaking change for 3.0.0: `serverRelativeUrl` properties changed to `server_relative_url`

### ISSUE THREAD

**Issue by emredjan** [vgrem/Office365-REST-Python-Client#1037]
In all places, sharepoint file and folder property `.serverRelativeUrl` is changed to `.server_relative_url`, breaking many existing flows (that work fine in 2.6.2) with errors similar to: `AttributeError: 'File' object has no attribute 'serverRelativeUrl'` in version 3.0.0

This is not listed as a breaking change in the release notes, nor there was any deprecation notice in prior versions.

Also, the change is (probably) not reflected in type stubs and the linters fail to recognize the new `.server_relative_url` property.

Tested in:

```
Python 3.14.7
office365-rest-python-client 3.0.0
```
