### ISSUE TITLE
Getting "'ResourcePath' object has no attribute 'collection'" on execute_query

### ISSUE THREAD

**Issue by vince2678** [vgrem/Office365-REST-Python-Client#680]
I've been getting this fairly often while trying to use some `DriveItem` methods (`upload`, `resumable_upload`). On uploads in particular, the upload works and the file is there on OneDrive, but an exception is thrown:

```
[2023-05-06 00:20:23,729: DEBUG/ForkPoolWorker-4] Traceback (most recent call last):
  File "utils.py", line 261, in upload_file
    return None, folder.upload(name, data).execute_query()
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/runtime/client_object.py", line 44, in execute_query
    self.context.execute_query()
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/runtime/client_runtime_context.py", line 181, in execute_query
    self.pending_request().execute_query(qry)
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/runtime/client_request.py", line 59, in execute_query
    self.process_response(response, query)
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/runtime/odata/request.py", line 68, in process_response
    self.map_json(response.json(), return_type, json_format)
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/runtime/odata/request.py", line 81, in map_json
    return_type.set_property(k, v, False)
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/entity.py", line 54, in set_property
    self._resource_path.normalize(value, inplace=True)
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/runtime/paths/entity.py", line 31, in normalize
    self._parent = self.collection
  File "/home/vienna/env3-3.8.13/lib/python3.8/site-packages/office365/onedrive/internal/paths/url.py", line 18, in collection
    self._collection = self.parent.collection
AttributeError: 'ResourcePath' object has no attribute 'collection'
```

Not sure if i'm doing anything wrong or what. I'm using v2.4.1 for reference.

**Comment by vince2678** [comment]
I'm using v2.4.1

**Comment by vince2678** [comment]
So i just monkeypatched this and seems to be fine.


```
# Patch method for UrlPath.
def patched_collection(self: UrlPath):
    # Check attr exists before access.
    while self.parent and hasattr(self.parent, 'collection') and self._collection is None:
            self._collection = self.parent.collection

    return self._collection

UrlPath.collection = property(patched_collection)
```

**Comment by gianfrancodemarco** [comment]
Hi, I'm having the same problem when calling `create_folder(...).execute_query()`.
However it works fine on 2.4.2.

**Comment by vince2678** [comment]
There was another similar issue with `UrlPath` that i got around with this patch on v2.4.1, not sure if it's already been addressed in later versions:

```
from office365.onedrive.driveitems.driveItem import DriveItem
from office365.onedrive.driveitems.item_preview_info import ItemPreviewInfo
from office365.onedrive.internal.paths.url import UrlPath
from office365.runtime.paths.entity import EntityPath
from office365.runtime.paths.resource_path import ResourcePath
from office365.runtime.client_result import ClientResult
from office365.runtime.queries.service_operation import ServiceOperationQuery

def patched_urlpath_collection(self: UrlPath):
    '''
    Patch method for UrlPath.

    The unpatched method can throw an exception because of missing parent attr on self.
    '''
    # Check attr exists before access.
    while self.parent and hasattr(self.parent, 'collection') and self._collection is None:
            self._collection = self.parent.collection

    return self._collection
```

**Comment by vince2678** [comment]
> There was another similar issue with `UrlPath` that i got around with this patch on v2.4.1, not sure if it's already been addressed in later versions:
> 
> ```
> from office365.onedrive.driveitems.driveItem import DriveItem
> from office365.onedrive.driveitems.item_preview_info import ItemPreviewInfo
> from office365.onedrive.internal.paths.url import UrlPath
> from office365.runtime.paths.entity import EntityPath
> from office365.runtime.paths.resource_path import ResourcePath
> from office365.runtime.client_result import ClientResult
> from office365.runtime.queries.service_operation import ServiceOperationQuery
> 
> def patched_urlpath_collection(self: UrlPath):
>     '''
>     Patch method for UrlPath.
> 
>     The unpatched method can throw an exception because of missing parent attr on self.
>     '''
>     # Check attr exists before access.
>     while self.parent and hasattr(self.parent, 'collection') and self._collection is None:
>             self._collection = self.parent.collection
> 
>     return self._collection
> ```

My bad, pasted the one I'd already mentioned before. Meant `ResourcePath`:

```
from office365.onedrive.driveitems.driveItem import DriveItem
from office365.onedrive.driveitems.item_preview_info import ItemPreviewInfo
from office365.onedrive.internal.paths.url import UrlPath
from office365.runtime.paths.entity import EntityPath
from office365.runtime.paths.resource_path import ResourcePath
from office365.runtime.client_result import ClientResult
from office365.runtime.queries.service_operation import ServiceOperationQuery


def patched_resourcepath_collection(self: ResourcePath):
    '''
    Patch method for ResourcePath.

    The unpatched method can throw an exception because of missing parent attr on self.
    '''
    if self._collection is None:
        if isinstance(self.parent, EntityPath) and hasattr(self.parent, 'collection'):
            self._collection = self.parent.collection
        elif hasattr(self.parent, 'parent'):
            self._collection = self.parent.parent

    return self._collection

```

**Comment by vgrem** [comment]
Closing this one since it has been addressed in [`2.5.0` release](https://github.com/vgrem/Office365-REST-Python-Client/releases/tag/2.5.0)
