### ISSUE TITLE
Problems with ListItem.get_item_by_id

### ISSUE THREAD

**Issue by pvoloshyn** [vgrem/Office365-REST-Python-Client#171]
Hi,

I'm trying to use the latest version (2.1.6-1) but I'm getting troubles in `ListItem.get_item_by_id`.

The code is simples and it works in version 2.1.5 :
```
item = ctx.web.lists.get_by_title('SampleList').get_item_by_id(some_valid_id)
ctx.load(item)
ctx.execute_query()
```

The error I got follows below:
```
\anaconda3\lib\site-packages\office365\sharepoint\listitem.py in set_property(self, name, value, serializable)
     85         if name == "Id":
     86             self._resource_path = ResourcePathServiceOperation(
---> 87                 "getItemById", [value], self._parent_collection.resourcePath)

AttributeError: 'NoneType' object has no attribute 'resourcePath'
```

I noticed that the example for list operations was deleted. 

Is there anything else I can do?

**Comment by vgrem** [comment]
Greetings,

thanks for catching this bug, it has been resolved in the latest commit.

Vadim
